spring.datasource.url=jdbc:sqlserver://143.110.239.84:1433;databaseName=nomina_db;encrypt=true;trustServerCertificate=true;loginTimeout=30;
spring.datasource.username=sa
spring.datasource.password=TuPasswordFuerte2026!