spring.application.name=nomina_api
server.port=8080
server.servlet.context-path=/api

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=none
// desactivado para mejorar rendimiento
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true